=== harryhurtad/DataConnectorMetaDataModel/src/main/resources/DataConnectorMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://com.dataconnector/schema/DataConnectorMetadata"
    xmlns:tns="http://com.dataconnector/schema/DataConnectorMetadata"
    elementFormDefault="qualified">
    <xsd:simpleType name="alias_field-def">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:complexType name="Field-def">
        <xsd:sequence>
            <xsd:element name="alias_field" type="tns:alias_field-def"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="Fields-def">
        <xsd:sequence>
            <xsd:element name="Field" type="tns:Field-def" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="alias_table-def">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:complexType name="table_override-def">
        <xsd:sequence>
            <xsd:element name="alias_table" type="tns:alias_table-def"></xsd:element>
            <xsd:element name="Fields" type="tns:Fields-def" maxOccurs="1" minOccurs="0"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="DataConnectorMetadata-def">
        <xsd:sequence>
            <xsd:element name="Tables" type="tns:Tables-def"></xsd:element>
            <xsd:element name="output_dir_jar" type="xsd:string"></xsd:element>
            <xsd:element name="dir_lib" type="xsd:time"/>
            <xsd:element name="JarInfoGenerate_def" type="tns:JarInfoGenerate-def"></xsd:element>
            <xsd:element name="package_name_gen" type="xsd:string"></xsd:element>
            <xsd:element name="jdbc_connection" type="tns:jdbc_connection-def"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="DataConnectorMetadata" type="tns:DataConnectorMetadata-def"></xsd:element>
    <xsd:complexType name="Tables-def">
        <xsd:sequence>
            <xsd:element name="table_override" type="tns:table_override-def" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="JarInfoGenerate-def">
        <xsd:sequence>
            <xsd:element name="provider" type="xsd:string"></xsd:element>
            <xsd:element name="version" type="xsd:string"></xsd:element>
            <xsd:element name="nameFile" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="jdbc_connection-def">
        <xsd:sequence>
            <xsd:element name="driverClass" type="xsd:string"></xsd:element>
            <xsd:element name="URL" type="xsd:string"></xsd:element>
            <xsd:element name="usuario" type="xsd:string"></xsd:element>
            <xsd:element name="password" type="xsd:string"></xsd:element>
            <xsd:element name="schemaBD" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== harryhurtad/DataConnectorMetaDataModel/src/main/java/com/dataconnector/xml/template/DataConnectorMetadata-conf.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : DataConnectorMetadata.xml
    Created on : 24 de mayo de 2016, 03:32 PM
    Author     : proveedor_hhurtado
    Description:
        Purpose of the document follows.
-->

<DataConnectorMetadata  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                        xmlns='http://com.dataconnector/schema/DataConnectorMetadata'
                        xsi:schemaLocation='http://com.dataconnector/schema/DataConnectorMetadata DataConnectorMetadata.xsd'>
    <output_dir_jar>C:\tmp\dataconnector_output</output_dir_jar>
    <dir_lib>C:\tmp\lib</dir_lib>
    <package_name_gen>com.prueba.dataconnector</package_name_gen>
    <JarInfoGenerate_def>
        <nameFile>DataConnectorMysqlMetadata</nameFile>
        <provider>UNICO</provider>
        <version>1.0</version>
    </JarInfoGenerate_def>
    <!-- Override de las tablas    -->
    <Tables> 
        <table_override id="dept_emp">
            <alias_table>deptEmp</alias_table>
            <Fields>
                <Field id="emp_no">
                    <alias_field>empId</alias_field>
                </Field>
                <Field id="dept_no">
                    <alias_field>deptId</alias_field>
                </Field>           
            </Fields>
        </table_override>
        <table_override id="departments">
            <alias_table>departPrueba</alias_table>       
        </table_override>
    </Tables>
</DataConnectorMetadata>
